import {
  ImpactNodeId,
  ImpactNodeState,
  RequirementChangePreset,
} from '../types/integration';

export const requirementChangePresets: RequirementChangePreset[] = [
  {
    id: 'sso-instead-of-api-keys',
    title: 'Customer changes: "Authentication must use SSO / OIDC instead of API keys"',
    description: 'Customer security policy mandates enterprise Okta / Azure AD / PingFederate federated single sign-on with ephemeral token exchanges instead of static API keys.',
    category: 'Auth',
    overallDelayDays: 8,
    overallCostDeltaUsd: 450,
    securityImpactSummary: 'Significantly strengthens identity perimeter by removing static secret exfiltration risks. Adds token validation latency and IdP availability dependency.',
    nodeImpacts: {
      customer: {
        nodeId: 'customer',
        label: 'Customer',
        status: 'reconfigured',
        changeTitle: 'Identity Provider Federation Binding',
        detail: 'Customer identity administrator must register OIDC client application, configure claim scopes, and share metadata discovery URL (.well-known/openid-configuration).',
        codeChanges: ['Customer IdP App Registration', 'OAuth Redirect URI configuration', 'Role / Group Claim mapping'],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 2,
      },
      identity: {
        nodeId: 'identity',
        label: 'Identity',
        status: 'high_risk',
        changeTitle: 'Token Broker & JWKS Caching Engine',
        detail: 'Replace static API Key verification filter with high-performance JWKS parser, JWT signature verification, audience assertion, and in-memory key cache.',
        codeChanges: ['src/auth/oidcValidator.ts', 'src/auth/jwksClient.ts', 'src/middleware/tokenIntrospection.ts'],
        latencyDeltaMs: 14,
        costDeltaMonthlyUsd: 120,
        timelineDelayDays: 4,
      },
      api: {
        nodeId: 'api',
        label: 'API',
        status: 'reconfigured',
        changeTitle: 'Authorization Header & Scope Enforcement',
        detail: 'API Gateway must inspect Bearer tokens, validate OAuth scopes (read:records, write:orders), and handle 401 WWW-Authenticate challenge headers.',
        codeChanges: ['infra/apigateway/authorizer.tf', 'src/api/middleware/requireScope.ts', 'openapi.yaml (SecuritySchemes)'],
        latencyDeltaMs: 4,
        costDeltaMonthlyUsd: 80,
        timelineDelayDays: 2,
      },
      data_transformation: {
        nodeId: 'data_transformation',
        label: 'Data Transformation',
        status: 'reconfigured',
        changeTitle: 'User Context & Actor Claims Enrichment',
        detail: 'Inject authenticated actor sub / email / tenant_id claims into downstream domain payload before transformation.',
        codeChanges: ['src/transforms/enrichContext.ts', 'src/schemas/canonicalEvent.ts'],
        latencyDeltaMs: 1,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 1,
      },
      internal_service: {
        nodeId: 'internal_service',
        label: 'Internal Service',
        status: 'affected',
        changeTitle: 'Tenant Isolation & Multi-Tenancy Routing',
        detail: 'Internal services must adopt tenant context propagation via OpenTelemetry baggage / gRPC metadata.',
        codeChanges: ['src/services/tenantContext.ts', 'src/client/grpcInterceptor.ts'],
        latencyDeltaMs: 2,
        costDeltaMonthlyUsd: 50,
        timelineDelayDays: 2,
      },
      database: {
        nodeId: 'database',
        label: 'Database',
        status: 'affected',
        changeTitle: 'Audit Ledger & User Attribution Columns',
        detail: 'Ensure audit trail records track authenticated sub claim rather than generic api_client_id.',
        codeChanges: ['migrations/20261101_add_user_sub_to_audit.sql', 'src/db/schema.ts'],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 1,
      },
      monitoring: {
        nodeId: 'monitoring',
        label: 'Monitoring',
        status: 'reconfigured',
        changeTitle: 'IdP Latency & Token Expiry Alerting',
        detail: 'Add Prometheus metrics for OIDC JWKS fetch errors, token validation rejection rates, and IdP downtime alerts.',
        codeChanges: ['observability/alerts/auth_failures.yaml', 'src/metrics/authMetrics.ts'],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 200,
        timelineDelayDays: 1,
      },
    },
  },
  {
    id: 'mtls-enforcement',
    title: 'Customer changes: "Customer mandates mTLS with private enterprise CA"',
    description: 'Customer infosec rejects standard public TLS and requires mutual client certificate verification with their internal DigiCert / HashiCorp Vault PKI.',
    category: 'Auth',
    overallDelayDays: 12,
    overallCostDeltaUsd: 680,
    securityImpactSummary: 'Maximum cryptographic transport assurance. Prevents any traffic from unauthorized machines. Requires strict certificate rotation lifecycle.',
    nodeImpacts: {
      customer: {
        nodeId: 'customer',
        label: 'Customer',
        status: 'affected',
        changeTitle: 'Client Certificate Provisioning',
        detail: 'Customer must generate client keys, issue certificates from Enterprise CA, and distribute via safe PKI pipelines.',
        codeChanges: ['PKI Certificate distribution workflow', 'Internal Root & Intermediate CA bundle exchange'],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 4,
      },
      identity: {
        nodeId: 'identity',
        label: 'Identity',
        status: 'high_risk',
        changeTitle: 'Truststore Validation & CRL/OCSP Checks',
        detail: 'Must validate client certificate Subject Alternative Name (SAN), expiration, and real-time revocation via OCSP.',
        codeChanges: ['src/security/ocspChecker.ts', 'src/auth/certValidator.ts', 'infra/pki/truststore.tf'],
        latencyDeltaMs: 25,
        costDeltaMonthlyUsd: 220,
        timelineDelayDays: 5,
      },
      api: {
        nodeId: 'api',
        label: 'API',
        status: 'high_risk',
        changeTitle: 'Perimeter TLS Termination Shift',
        detail: 'Standard Layer 7 CDN cannot terminate custom private CAs; must route through AWS NLB or dedicated Envoy reverse proxies.',
        codeChanges: ['infra/networking/nlb_listener.tf', 'envoy/envoy.yaml (tls_context)'],
        latencyDeltaMs: 15,
        costDeltaMonthlyUsd: 350,
        timelineDelayDays: 6,
      },
      data_transformation: {
        nodeId: 'data_transformation',
        label: 'Data Transformation',
        status: 'unchanged',
        changeTitle: 'No Direct Impact',
        detail: 'Data transformation pipeline consumes parsed payload downstream of TLS termination.',
        codeChanges: [],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 0,
      },
      internal_service: {
        nodeId: 'internal_service',
        label: 'Internal Service',
        status: 'unchanged',
        changeTitle: 'Service Mesh Unchanged',
        detail: 'Internal service-to-service communication remains on internal mTLS mesh.',
        codeChanges: [],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 0,
      },
      database: {
        nodeId: 'database',
        label: 'Database',
        status: 'unchanged',
        changeTitle: 'Persistence Unchanged',
        detail: 'Database schemas and queries remain unaffected.',
        codeChanges: [],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 0,
      },
      monitoring: {
        nodeId: 'monitoring',
        label: 'Monitoring',
        status: 'reconfigured',
        changeTitle: 'Certificate Expiration Telemetry',
        detail: 'Add proactive alerts 30, 14, and 7 days prior to client certificate expiration to prevent silent hard cutoffs.',
        codeChanges: ['observability/alerts/cert_expiry_alert.yaml', 'scripts/check_cert_expiry.sh'],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 110,
        timelineDelayDays: 1,
      },
    },
  },
  {
    id: 'rate-limit-slashed',
    title: 'Customer changes: "Rate limit slashed to 15 RPS with strict concurrency cap"',
    description: 'Customer legacy backend experiences resource exhaustion; customer enforces a strict ceiling of 15 requests per second and max 5 concurrent in-flight requests.',
    category: 'Rate Limits',
    overallDelayDays: 6,
    overallCostDeltaUsd: 220,
    securityImpactSummary: 'Protects customer backend from brownouts, but introduces massive queuing and SLA breach risks for high-volume transactions.',
    nodeImpacts: {
      customer: {
        nodeId: 'customer',
        label: 'Customer',
        status: 'reconfigured',
        changeTitle: 'Strict Throttling Policy Agreement',
        detail: 'Customer acknowledges that peak transactions will experience queuing delay or require batched consolidation.',
        codeChanges: ['SLA addendum adjustment'],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 1,
      },
      identity: {
        nodeId: 'identity',
        label: 'Identity',
        status: 'unchanged',
        changeTitle: 'Unchanged',
        detail: 'Identity authentication mechanics unaffected.',
        codeChanges: [],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 0,
      },
      api: {
        nodeId: 'api',
        label: 'API',
        status: 'reconfigured',
        changeTitle: 'Leaky Bucket Rate Limiter Modification',
        detail: 'Recalibrate API gateway usage plans; implement 429 Too Many Requests response with accurate Retry-After backoff headers.',
        codeChanges: ['infra/apigateway/usage_plan.tf', 'src/middleware/rateLimiter.ts'],
        latencyDeltaMs: 2,
        costDeltaMonthlyUsd: 40,
        timelineDelayDays: 2,
      },
      data_transformation: {
        nodeId: 'data_transformation',
        label: 'Data Transformation',
        status: 'affected',
        changeTitle: 'Batch Aggregation / Compaction Buffer',
        detail: 'Combine individual item events into consolidated array payloads where possible to maximize per-request utility under 15 RPS cap.',
        codeChanges: ['src/transforms/batchAggregator.ts', 'src/queues/compactorWorker.ts'],
        latencyDeltaMs: 40,
        costDeltaMonthlyUsd: 60,
        timelineDelayDays: 3,
      },
      internal_service: {
        nodeId: 'internal_service',
        label: 'Internal Service',
        status: 'high_risk',
        changeTitle: 'Outbound Queue Buffering & Concurrency Semaphore',
        detail: 'Cannot send outbound calls synchronously anymore! Must enqueue all requests into SQS/PubSub with worker pool limited to 15 threads.',
        codeChanges: ['src/queues/outboundRatePacer.ts', 'src/workers/throttledDispatcher.ts'],
        latencyDeltaMs: 250,
        costDeltaMonthlyUsd: 90,
        timelineDelayDays: 4,
      },
      database: {
        nodeId: 'database',
        label: 'Database',
        status: 'affected',
        changeTitle: 'Queue State & Outbox Table Indexing',
        detail: 'Outbox table will experience higher row retention while waiting for throttled dispatch workers.',
        codeChanges: ['migrations/20261102_index_outbox_queue.sql'],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 30,
        timelineDelayDays: 1,
      },
      monitoring: {
        nodeId: 'monitoring',
        label: 'Monitoring',
        status: 'high_risk',
        changeTitle: 'Queue Backlog & Age-of-Oldest-Message Alerts',
        detail: 'Critical alarms when outbound queue backlog exceeds 1,000 items or oldest message age exceeds 3 minutes.',
        codeChanges: ['observability/alerts/queue_backlog_alarms.yaml'],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 1,
      },
    },
  },
  {
    id: 'privatelink-only-no-internet',
    title: 'Customer changes: "Egress internet blocked; must route via PrivateLink / Private Service Connect"',
    description: 'Customer InfoSec updates compliance mandate: zero traffic may touch the public internet. All traffic must transit AWS PrivateLink / Azure Private Endpoint.',
    category: 'Networking',
    overallDelayDays: 14,
    overallCostDeltaUsd: 850,
    securityImpactSummary: 'Eliminates perimeter exposure, internet MITM risks, and IP allowlist brittleness. Major infrastructure overhaul on networking layer.',
    nodeImpacts: {
      customer: {
        nodeId: 'customer',
        label: 'Customer',
        status: 'high_risk',
        changeTitle: 'VPC Endpoint Creation & Account Whitelist',
        detail: 'Customer NetOps must accept Endpoint Service invitation, allocate private IP subnets, and configure private hosted DNS zones.',
        codeChanges: ['Customer VPC Endpoint Service Acceptance', 'Internal Route Table Updates'],
        latencyDeltaMs: -5,
        costDeltaMonthlyUsd: 150,
        timelineDelayDays: 5,
      },
      identity: {
        nodeId: 'identity',
        label: 'Identity',
        status: 'reconfigured',
        changeTitle: 'Private IdP Resolution',
        detail: 'OAuth token endpoints must resolve to private internal IPs rather than public auth0.com or okta.com endpoints.',
        codeChanges: ['src/config/internalAuthEndpoints.ts'],
        latencyDeltaMs: -2,
        costDeltaMonthlyUsd: 50,
        timelineDelayDays: 2,
      },
      api: {
        nodeId: 'api',
        label: 'API',
        status: 'high_risk',
        changeTitle: 'Private Network Load Balancer (NLB) Shift',
        detail: 'Dismantle public API Gateway; provision VPC Endpoint Service backed by Private Network Load Balancer inside target VPC.',
        codeChanges: ['infra/networking/private_endpoint_service.tf', 'infra/networking/nlb.tf'],
        latencyDeltaMs: -8,
        costDeltaMonthlyUsd: 420,
        timelineDelayDays: 7,
      },
      data_transformation: {
        nodeId: 'data_transformation',
        label: 'Data Transformation',
        status: 'unchanged',
        changeTitle: 'Pipeline Logic Intact',
        detail: 'Core schema transformations operate inside private compute tier without network awareness.',
        codeChanges: [],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 0,
      },
      internal_service: {
        nodeId: 'internal_service',
        label: 'Internal Service',
        status: 'reconfigured',
        changeTitle: 'Private DNS Resolution & Strict VPC Egress',
        detail: 'Internal services must bind to private VPC endpoints for all cloud services (S3, Secrets Manager, SQS).',
        codeChanges: ['infra/vpc/vpc_endpoints_aws_services.tf'],
        latencyDeltaMs: -3,
        costDeltaMonthlyUsd: 180,
        timelineDelayDays: 3,
      },
      database: {
        nodeId: 'database',
        label: 'Database',
        status: 'unchanged',
        changeTitle: 'Isolated in DB Subnets',
        detail: 'Database already resides in isolated database private subnets.',
        codeChanges: [],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 0,
      },
      monitoring: {
        nodeId: 'monitoring',
        label: 'Monitoring',
        status: 'reconfigured',
        changeTitle: 'Private VPC Flow Logs & Endpoint Health',
        detail: 'Monitor VPC Flow Logs for rejected TCP packets and NLB target health check probes across ENIs.',
        codeChanges: ['observability/cloudwatch/vpc_flow_logs.tf', 'alerts/nlb_unhealthy_hosts.yaml'],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 50,
        timelineDelayDays: 2,
      },
    },
  },
  {
    id: 'hipaa-phi-strict',
    title: 'Customer changes: "Customer requires HIPAA BAA & zero PII/PHI in persistence logs"',
    description: 'Legal & InfoSec mandate strict HIPAA compliance: signed Business Associate Agreement, field-level encryption for PHI, zero plaintext PHI in logs or error traces.',
    category: 'Compliance',
    overallDelayDays: 10,
    overallCostDeltaUsd: 520,
    securityImpactSummary: 'Enforces strict medical data confidentiality. Requires automated log sanitization filters and customer-managed KMS key hierarchies.',
    nodeImpacts: {
      customer: {
        nodeId: 'customer',
        label: 'Customer',
        status: 'affected',
        changeTitle: 'Execute BAA Agreement & Security Audit',
        detail: 'Legal team signs BAA, verifies SOC2 Type II report, and approves key management protocol.',
        codeChanges: ['Legal BAA execution', 'Annual audit sign-off'],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 4,
      },
      identity: {
        nodeId: 'identity',
        label: 'Identity',
        status: 'reconfigured',
        changeTitle: 'MFA Enforcement & Role-Based Access Scopes',
        detail: 'Enforce MFA for all administrative identities and strict scope separation for clinical data readers vs writers.',
        codeChanges: ['src/auth/mfaPolicy.ts', 'src/auth/rbacEnforcer.ts'],
        latencyDeltaMs: 5,
        costDeltaMonthlyUsd: 60,
        timelineDelayDays: 2,
      },
      api: {
        nodeId: 'api',
        label: 'API',
        status: 'reconfigured',
        changeTitle: 'Payload Redaction in Access Logs',
        detail: 'Strip request bodies and query parameters from API Gateway access logs to ensure zero PHI leakage into CloudWatch.',
        codeChanges: ['infra/apigateway/access_logging_format.tf'],
        latencyDeltaMs: 1,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 2,
      },
      data_transformation: {
        nodeId: 'data_transformation',
        label: 'Data Transformation',
        status: 'high_risk',
        changeTitle: 'Envelope Encryption & PII Masking Pipeline',
        detail: 'Transform pipeline must perform field-level KMS envelope encryption on all PHI fields (Name, MRN, DOB, vitals) before queueing.',
        codeChanges: ['src/crypto/envelopeEncryption.ts', 'src/transforms/maskPhi.ts', 'src/schemas/phiFields.ts'],
        latencyDeltaMs: 18,
        costDeltaMonthlyUsd: 280,
        timelineDelayDays: 5,
      },
      internal_service: {
        nodeId: 'internal_service',
        label: 'Internal Service',
        status: 'high_risk',
        changeTitle: 'Zero-PHI Logging Filter in Logger Libraries',
        detail: 'Pino / Winston logger interceptors must redact regex patterns matching SSNs, MRNs, and patient names from all output stdout.',
        codeChanges: ['src/logging/phiRedactFilter.ts', 'src/errors/safeErrorSerializer.ts'],
        latencyDeltaMs: 2,
        costDeltaMonthlyUsd: 40,
        timelineDelayDays: 3,
      },
      database: {
        nodeId: 'database',
        label: 'Database',
        status: 'reconfigured',
        changeTitle: 'TDE Encryption with Customer Managed Key (CMK)',
        detail: 'Enable Transparent Data Encryption using customer AWS KMS / Azure Key Vault CMK with automated key rotation.',
        codeChanges: ['infra/database/kms_cmk.tf', 'migrations/20261103_alter_table_encrypt.sql'],
        latencyDeltaMs: 2,
        costDeltaMonthlyUsd: 140,
        timelineDelayDays: 2,
      },
      monitoring: {
        nodeId: 'monitoring',
        label: 'Monitoring',
        status: 'reconfigured',
        changeTitle: 'Immutable Audit Trail & DLP Log Scanning',
        detail: 'Enable AWS CloudTrail / Azure Activity Log immutable S3 Object Lock and automated DLP scan alerts for accidental PII leaks.',
        codeChanges: ['infra/security/dlp_scanner.tf', 'observability/alerts/phi_leak_alert.yaml'],
        latencyDeltaMs: 0,
        costDeltaMonthlyUsd: 0,
        timelineDelayDays: 2,
      },
    },
  },
];

export function simulateRequirementChange(changeId: string): RequirementChangePreset {
  const found = requirementChangePresets.find((p) => p.id === changeId);
  return found || requirementChangePresets[0];
}
