import React, { useState } from 'react';
import { CustomerProfile, ReadinessReport, FrictionAnalysis } from '../types/integration';
import {
  FileText,
  Printer,
  Copy,
  Check,
  X,
  ShieldCheck,
  AlertTriangle,
  XCircle,
  CheckCircle2,
  Calendar,
  Building,
} from 'lucide-react';

interface ClientFacingReportModalProps {
  profile: CustomerProfile;
  report: ReadinessReport;
  analysis: FrictionAnalysis;
  onClose: () => void;
}

export const ClientFacingReportModal: React.FC<ClientFacingReportModalProps> = ({
  profile,
  report,
  analysis,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopyMarkdown = () => {
    const md = `# Integration Readiness & Architecture Assessment
**Customer:** ${profile.name}
**Industry:** ${profile.industry}
**Target Deployment:** ${profile.deployment.target.toUpperCase()} (${profile.deployment.region})
**Go-Live Target Date:** ${profile.targetGoLiveDate}
**Assessment Status:** ${report.status} (Confidence: ${report.confidencePercentage}%)

---

### Executive Summary
${report.executiveSummary}

**Estimated Time-to-First-Request:** ${report.timeToFirstRequest}
**Integration Friction Score:** ${analysis.overallScore}/100 (${analysis.level})

---

### Critical Blockers & Mandatory Prerequisites
${report.hardBlockers.length > 0 ? `\n#### Hard Blockers (Must Remediate Before Production)\n${report.hardBlockers.map(b => `- ${b}`).join('\n')}` : ''}

${report.mandatoryConditions.length > 0 ? `\n#### Mandatory Conditions for Pilot Launch\n${report.mandatoryConditions.map(c => `- ${c}`).join('\n')}` : ''}

---

### Architectural Dimension Summary
- **API Spec & Format:** ${profile.apiSpec.format} (${profile.apiSpec.endpointsCount} endpoints)
- **Authentication:** ${profile.auth.mechanism.replace(/_/g, ' ').toUpperCase()} (${profile.auth.rotationPolicy})
- **Rate Limit Policy:** ${profile.rateLimits.rpsLimit} RPS sustained / ${profile.rateLimits.burstLimit} RPS burst
- **Network Transport:** ${profile.networking.type.replace(/_/g, ' ')} (Strict Firewall: ${profile.networking.strictEgressFirewall})
- **Compliance Alignment:** ${profile.compliance.soc2 ? 'SOC 2, ' : ''}${profile.compliance.pciDss ? 'PCI-DSS, ' : ''}${profile.compliance.hipaa ? 'HIPAA' : 'Standard Enterprise'}

---

Generated by IntegrationOS Implementation Intelligence Engine
`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-3 sm:p-6 overflow-y-auto">
      <div className="bg-zinc-950 border border-zinc-800 rounded-xl max-w-3xl w-full max-h-[90vh] flex flex-col shadow-2xl">
        {/* Modal Top Bar */}
        <div className="flex items-center justify-between p-4 border-b border-zinc-800 bg-zinc-900/60">
          <div className="flex items-center gap-2">
            <FileText className="w-4 h-4 text-emerald-400" />
            <h3 className="font-semibold text-zinc-100 text-sm">
              Client-Facing Integration Readiness Memo
            </h3>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="px-2.5 py-1 text-xs font-mono rounded bg-zinc-800 hover:bg-zinc-700 text-zinc-200 border border-zinc-700 flex items-center gap-1.5 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy MD'}</span>
            </button>
            <button
              onClick={handlePrint}
              className="px-2.5 py-1 text-xs font-mono rounded bg-zinc-800 hover:bg-zinc-700 text-zinc-200 border border-zinc-700 flex items-center gap-1.5 transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>
            <button
              onClick={onClose}
              className="p-1 rounded text-zinc-400 hover:text-zinc-200"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Scrollable Memo Body */}
        <div className="p-6 overflow-y-auto space-y-6 text-xs text-zinc-300 font-sans">
          {/* Header Memo Banner */}
          <div className="border-b border-zinc-800 pb-4">
            <div className="text-[10px] font-mono uppercase tracking-widest text-emerald-400 mb-1">
              Technical Architecture & Implementation Intelligence
            </div>
            <h1 className="text-xl font-bold text-zinc-100 tracking-tight">
              Integration Readiness Memo: {profile.name}
            </h1>
            <div className="flex flex-wrap items-center gap-3 text-zinc-400 mt-2 text-xs">
              <span className="flex items-center gap-1">
                <Building className="w-3.5 h-3.5" /> {profile.industry}
              </span>
              <span aria-hidden="true" className="text-zinc-700">·</span>
              <span className="flex items-center gap-1">
                <Calendar className="w-3.5 h-3.5" /> Target Go-Live: {profile.targetGoLiveDate}
              </span>
              <span aria-hidden="true" className="text-zinc-700">·</span>
              <span className="font-mono text-zinc-300">
                Cloud: {profile.deployment.target.toUpperCase()} ({profile.deployment.region})
              </span>
            </div>
          </div>

          {/* Readiness Status Box */}
          <div className="p-4 rounded-lg bg-zinc-900 border border-zinc-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <div className="text-[10px] uppercase font-mono text-zinc-500 mb-0.5">
                Executive Verdict
              </div>
              <div className="flex items-center gap-2">
                {report.status === 'READY' && <CheckCircle2 className="w-5 h-5 text-emerald-400" />}
                {report.status === 'READY WITH CONDITIONS' && <AlertTriangle className="w-5 h-5 text-amber-400" />}
                {report.status === 'BLOCKED' && <XCircle className="w-5 h-5 text-rose-400" />}
                <span className="text-lg font-bold font-mono text-zinc-100">{report.status}</span>
              </div>
            </div>

            <div className="flex items-center gap-4 text-xs font-mono">
              <div>
                <div className="text-zinc-500 text-[10px]">Confidence</div>
                <div className="font-bold text-emerald-400">{report.confidencePercentage}%</div>
              </div>
              <div className="h-6 w-px bg-zinc-800" />
              <div>
                <div className="text-zinc-500 text-[10px]">Time-to-First-Request</div>
                <div className="font-bold text-zinc-200">{report.timeToFirstRequest}</div>
              </div>
              <div className="h-6 w-px bg-zinc-800" />
              <div>
                <div className="text-zinc-500 text-[10px]">Friction Score</div>
                <div className="font-bold text-zinc-200">{analysis.overallScore}/100</div>
              </div>
            </div>
          </div>

          {/* Executive Narrative */}
          <div>
            <h4 className="font-semibold text-zinc-200 text-sm mb-1.5">
              1. Executive Summary & Assessment
            </h4>
            <p className="leading-relaxed text-zinc-300">
              {report.executiveSummary}
            </p>
          </div>

          {/* Blockers & Prerequisites */}
          {report.hardBlockers.length > 0 && (
            <div className="p-3.5 rounded-lg bg-rose-950/30 border border-rose-900/40">
              <h4 className="font-semibold text-rose-300 text-xs mb-1.5 flex items-center gap-1.5">
                <XCircle className="w-4 h-4 text-rose-400" />
                <span>Critical Hard Blockers (Zero Traffic Permitted)</span>
              </h4>
              <ul className="list-disc list-inside space-y-1 text-rose-200/90 text-xs">
                {report.hardBlockers.map((b, i) => (
                  <li key={i}>{b}</li>
                ))}
              </ul>
            </div>
          )}

          {report.mandatoryConditions.length > 0 && (
            <div className="p-3.5 rounded-lg bg-amber-950/30 border border-amber-900/40">
              <h4 className="font-semibold text-amber-300 text-xs mb-1.5 flex items-center gap-1.5">
                <AlertTriangle className="w-4 h-4 text-amber-400" />
                <span>Mandatory Conditions for Pre-Production Acceptance</span>
              </h4>
              <ul className="list-disc list-inside space-y-1 text-amber-200/90 text-xs">
                {report.mandatoryConditions.map((c, i) => (
                  <li key={i}>{c}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Architectural Alignment Grid */}
          <div>
            <h4 className="font-semibold text-zinc-200 text-sm mb-2">
              2. Architectural & Technical Parameters
            </h4>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5 font-mono text-[11px]">
              <div className="p-2 rounded bg-zinc-900 border border-zinc-800">
                <div className="text-zinc-500 text-[10px]">API Format</div>
                <div className="text-zinc-200">{profile.apiSpec.format}</div>
              </div>
              <div className="p-2 rounded bg-zinc-900 border border-zinc-800">
                <div className="text-zinc-500 text-[10px]">Authentication</div>
                <div className="text-zinc-200">{profile.auth.mechanism}</div>
              </div>
              <div className="p-2 rounded bg-zinc-900 border border-zinc-800">
                <div className="text-zinc-500 text-[10px]">Rate Limit</div>
                <div className="text-zinc-200">{profile.rateLimits.rpsLimit} RPS</div>
              </div>
              <div className="p-2 rounded bg-zinc-900 border border-zinc-800">
                <div className="text-zinc-500 text-[10px]">Networking</div>
                <div className="text-zinc-200">{profile.networking.type}</div>
              </div>
              <div className="p-2 rounded bg-zinc-900 border border-zinc-800">
                <div className="text-zinc-500 text-[10px]">Database Engine</div>
                <div className="text-zinc-200">{profile.database.engine}</div>
              </div>
              <div className="p-2 rounded bg-zinc-900 border border-zinc-800">
                <div className="text-zinc-500 text-[10px]">Compliance</div>
                <div className="text-zinc-200">
                  {profile.compliance.soc2 ? 'SOC2 ' : ''}
                  {profile.compliance.hipaa ? 'HIPAA ' : ''}
                  {profile.compliance.pciDss ? 'PCI' : 'Standard'}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-zinc-800 bg-zinc-900/60 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-md bg-zinc-800 hover:bg-zinc-700 text-zinc-200 text-xs font-medium"
          >
            Close Memo
          </button>
        </div>
      </div>
    </div>
  );
};
